<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
      <PackageReference Include="Npgsql" Version="10.0.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ukinee.Infrastructure.Options\Ukinee.Infrastructure.Options.csproj" />
      <ProjectReference Include="..\Ukinee.Users.Domain.Models\Ukinee.Users.Domain.Models.csproj" />
      <ProjectReference Include="..\Ukinee.Users.Infrastructure\Ukinee.Users.Infrastructure.csproj" />
    </ItemGroup>

</Project>
