<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
      <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ukinee.DbAccess\Ukinee.DbAccess.csproj" />
      <ProjectReference Include="..\Ukinee.Infrastructure.Ddd.Common\Ukinee.Infrastructure.Ddd.Common.csproj" />
      <ProjectReference Include="..\Ukinee.Infrastructure.Ddd.Synchronization\Ukinee.Infrastructure.Ddd.Synchronization.csproj" />
    </ItemGroup>

</Project>
