using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Ukinee.Common.Identifiers.Attributes;

namespace Ukinee.Common.Identifiers.SourceGenerators.Identifiers
{
    [Generator]
    public class EntityIdentifierAttributeGenerator : IIncrementalGenerator
    {
        private const string TargetAttributeName = nameof(HasIdentifierAttribute);

        private static readonly DiagnosticDescriptor NotPartialError = new DiagnosticDescriptor(
            id: "ENID001",
            title: "Type must be partial",
            messageFormat: "Type '{0}' must be partial",
            category: "IdentifierGenerator",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true
        );

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entityDeclarations = context
                .SyntaxProvider.CreateSyntaxProvider(
                    predicate: (node, _) => GeneratorUtilities.IsClassOrRecordSyntax(node),
                    transform: (ctx, _) => GetEntityInfo(ctx)
                )
                .Where(info => info != null);

            context.RegisterSourceOutput(entityDeclarations, GenerateCode);
        }

        private static EntityInfo GetEntityInfo(GeneratorSyntaxContext context)
        {
            var typeDecl = (TypeDeclarationSyntax)context.Node;

            INamedTypeSymbol classSymbol = context.SemanticModel.GetDeclaredSymbol(typeDecl);

            if (classSymbol == null)
                return null;

            var attr = GeneratorUtilities.GetAttribute(classSymbol, TargetAttributeName);

            if (attr == null || attr.ConstructorArguments.Length == 0)
                return null;

            var idStructSymbol = attr.ConstructorArguments[0].Value as INamedTypeSymbol;

            if (idStructSymbol == null)
                return null;

            var location = GeneratorUtilities.GetIdentifierLocation(typeDecl);

            if (!GeneratorUtilities.IsPartial(typeDecl))
            {
                return new EntityInfo(NotPartialError, location, classSymbol.Name);
            }

            var properties = GeneratorUtilities
                .GetPublicInstanceProperties(idStructSymbol)
                .Select(p => (p.Name, p.Type.ToDisplayString()))
                .ToImmutableArray();

            if (properties.IsEmpty)
                return null;

            string typeKeyword = GeneratorUtilities.GetTypeKindKeyword(typeDecl);

            return new EntityInfo(
                classSymbol.ContainingNamespace.ToDisplayString(),
                classSymbol.Name,
                typeKeyword,
                idStructSymbol.ToDisplayString(),
                properties
            );
        }

        private static void GenerateCode(SourceProductionContext context, EntityInfo info)
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "GEN001",
                        "Debug",
                        "Initialize called!",
                        "Debug",
                        DiagnosticSeverity.Warning,
                        true
                    ),
                    Location.None
                )
            );

            if (!info.IsValid)
            {
                context.ReportDiagnostic(Diagnostic.Create(info.ErrorDescriptor, info.Location, info.ErrorArgs));

                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial {info.TypeKeyword} {info.ClassName}");
            sb.AppendLine("    {");

            foreach (var prop in info.Properties)
            {
                sb.AppendLine($"        public {prop.Type} {prop.Name} {{ get; private set; }}");
            }

            sb.AppendLine();

            sb.AppendLine($"        public required partial {info.IdentifierType} Identifier");
            sb.AppendLine("        {");
            sb.AppendLine($"            get => new() {{ {string.Join(", ", info.Properties.Select(p => $"{p.Name} = this.{p.Name}"))} }};");
            sb.AppendLine($"            init => ({string.Join(", ", info.Properties.Select(p => $"this.{p.Name}"))}) = ({string.Join(", ", info.Properties.Select(p => $"value.{p.Name}"))});");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{info.ClassName}_HasIdentifier.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private class EntityInfo
        {
            public string Namespace { get; } = string.Empty;
            public string ClassName { get; } = string.Empty;
            public string TypeKeyword { get; } = string.Empty;
            public string IdentifierType { get; } = string.Empty;
            public ImmutableArray<(string Name, string Type)> Properties { get; } = ImmutableArray<(string, string)>.Empty;

            public bool IsValid { get; }
            public Location Location { get; } = Location.None;
            public DiagnosticDescriptor ErrorDescriptor { get; }
            public string[] ErrorArgs { get; }

            public EntityInfo(string ns, string className, string typeKeyword, string idType, ImmutableArray<(string, string)> properties)
            {
                Namespace = ns;
                ClassName = className;
                TypeKeyword = typeKeyword;
                IdentifierType = idType;
                Properties = properties;
                IsValid = true;
            }

            public EntityInfo(DiagnosticDescriptor error, Location loc, params string[] args)
            {
                ErrorDescriptor = error;
                Location = loc;
                ErrorArgs = args;
                IsValid = false;
            }
        }
    }
}
