using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Ukinee.Common.Identifiers.Attributes;

namespace Ukinee.Common.Identifiers.SourceGenerators.Identifiers
{
    [Generator]
    public class RouteParamsGenerator : IIncrementalGenerator
    {
        private const string AttributeName = nameof(RouteParamsIdentifierAttribute);
        private const string IdentifierAttributeName = nameof(IdentifierAttribute);

        private static readonly DiagnosticDescriptor MissingIdentifierAttributeError = new DiagnosticDescriptor(
            id: "RPG001",
            title: "Missing IdentifierAttribute",
            messageFormat: "The struct '{0}' must also have [IdentifierAttribute] to use [RouteParamsIdentifier]",
            category: "RouteParamsGenerator",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true
        );

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structInfos = context
                .SyntaxProvider
                .CreateSyntaxProvider(
                    predicate:  (node, _) => GeneratorUtilities.IsStructSyntax(node),
                    transform:  (ctx, _) => GetStructInfo(ctx)
                )
                .Where( info => info != null);

            context.RegisterSourceOutput(structInfos,  GenerateCode);
        }

        private static RouteStructInfo GetStructInfo(GeneratorSyntaxContext context)
        {
            var typeDecl = (TypeDeclarationSyntax)context.Node;
            var typeSymbol = context.SemanticModel.GetDeclaredSymbol(typeDecl) as INamedTypeSymbol;

            if (typeSymbol == null)
                return null;

            var routeAttr = GeneratorUtilities.GetAttribute(typeSymbol, AttributeName);

            if (routeAttr == null)
                return null;

            if (GeneratorUtilities.GetAttribute(typeSymbol, IdentifierAttributeName) == null)
            {
                var location = GeneratorUtilities.GetIdentifierLocation(typeDecl);

                return new RouteStructInfo { IsValid = false, Error = Diagnostic.Create(MissingIdentifierAttributeError, location, typeSymbol.Name) };
            }

            var excludedNames = routeAttr
                .ConstructorArguments
                .SelectMany(arg => arg.Values.Select(v => v.Value?.ToString() ?? ""))
                .ToImmutableHashSet();

            var routeProperties = GeneratorUtilities
                .GetPublicInstanceProperties(typeSymbol)
                .Where(p => !excludedNames.Contains(p.Name))
                .Select(p => new PropertyInfo(p.Name, GetRouteConstraint(p.Type), p.Type.ToDisplayString()))
                .ToImmutableList();

            return new RouteStructInfo {
                IsValid = true,
                Namespace = typeSymbol.ContainingNamespace?.ToString() ?? "Global",
                OriginalTypeName = typeSymbol.Name,
                Properties = routeProperties,
                IsRecord = typeDecl.IsKind(SyntaxKind.RecordStructDeclaration)
            };
        }

        private static string GetRouteConstraint(ITypeSymbol type)
        {
            var typeName = type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

            switch (typeName)
            {
                case "Guid": return "guid";

                case "int":
                case "Int32":
                    return "int";

                case "long":
                case "Int64":
                    return "long";

                case "bool":
                case "Boolean":
                    return "bool";

                case "DateTime": return "datetime";
                case "decimal": return "decimal";
                case "float": return "float";
                case "double": return "double";
                default: return "";
            }
        }

        private static void GenerateCode(SourceProductionContext context, RouteStructInfo info)
        {
            if (!info.IsValid && info.Error != null)
            {
                context.ReportDiagnostic(info.Error);

                return;
            }

            var sb = new StringBuilder();
            var paramsTypeName = $"{info.OriginalTypeName}Params";

            sb.AppendLine("// <auto-generated />");

            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public readonly partial record struct {paramsTypeName} : Ukinee.Infrastructure.Ddd.External.Api.Domain.IRouteParams<{paramsTypeName}, {info.OriginalTypeName}>");
            sb.AppendLine("    {");

            foreach (var prop in info.Properties)
            {
                sb.AppendLine($"        public required {prop.FullTypeName} {prop.Name} {{ get; init; }}");
            }

            sb.AppendLine();

            sb.AppendLine($"        public static {paramsTypeName} FromIdentifier({info.OriginalTypeName} identifier)");
            sb.AppendLine("        {");
            sb.AppendLine($"            return new {paramsTypeName} {{");

            foreach (var prop in info.Properties)
            {
                sb.AppendLine($"                {prop.Name} = identifier.{prop.Name},");
            }

            sb.AppendLine($"            }};");
            sb.AppendLine("        }");

            sb.AppendLine();

            var path = string.Join("/", info.Properties.Select(p => $"{{{p.Name}}}"));

            sb.AppendLine($"        public string Path => $\"{path}\";");

            sb.AppendLine();

            var templatePath = string.Join("/", info.Properties.Select(p => string.IsNullOrEmpty(p.Constraint) ? $"{{{p.Name}}}" : $"{{{p.Name}:{p.Constraint}}}"));

            sb.AppendLine($"        public static string RouteTemplate => \"{templatePath}\";");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource($"{paramsTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private class RouteStructInfo
        {
            public bool IsValid { get; set; }
            public string Namespace { get; set; } = "";
            public string OriginalTypeName { get; set; } = "";
            public ImmutableList<PropertyInfo> Properties { get; set; } = ImmutableList<PropertyInfo>.Empty;
            public bool IsRecord { get; set; }
            public Diagnostic Error { get; set; }
        }

        private class PropertyInfo
        {
            public PropertyInfo(string name, string constraint, string fullTypeName)
            {
                Constraint = constraint;
                FullTypeName = fullTypeName;
                Name = name;
            }

            public string Constraint { get; }
            public string FullTypeName { get; }
            public string Name { get; }
        }
    }
}
