<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Frameworks\Ukinee.Common.Identifiers\Ukinee.Common.Identifiers.csproj"/>
        <ProjectReference Include="..\..\Frameworks\Ukinee.Infrastructure.Ddd.Common\Ukinee.Infrastructure.Ddd.Common.csproj"/>

        <ProjectReference Include="$(SourceGeneratorsPath)Ukinee.Common.Identifiers.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />

        <ProjectReference Include="..\..\Frameworks\Ukinee.Infrastructure.Ddd.External.Api.Domain\Ukinee.Infrastructure.Ddd.External.Api.Domain.csproj" />

        <ProjectReference Include="..\Examples.Server.Domain.Models\Examples.Server.Domain.Models.csproj" />
    </ItemGroup>
</Project>
